/*
 * Generated by XDoclet - Do not edit!
 */
package com.gotoque.torotask.negocio.workflow.ejb;

/**
 * Session layer for WFMotorConsulta.
 * 
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class WFMotorConsultaSession extends WFMotorConsultaBean implements
		javax.ejb.SessionBean {
	public void ejbActivate() throws javax.ejb.EJBException,
			java.rmi.RemoteException {

		super.ejbActivate();
	}

	public void ejbPassivate() throws javax.ejb.EJBException,
			java.rmi.RemoteException {
		super.ejbPassivate();
	}

	public void setSessionContext(javax.ejb.SessionContext ctx)
			throws javax.ejb.EJBException {
		super.setSessionContext(ctx);
	}

	public void unsetSessionContext() {
	}

	public void ejbRemove() throws javax.ejb.EJBException,
			java.rmi.RemoteException {
		super.ejbRemove();
	}

	public void ejbCreate() throws javax.ejb.CreateException {
	}

}
